version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Adicione outras variáveis de ambiente necessárias aqui
    restart: unless-stopped
